# Machine Learning

## Imports

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_percentage_error

## Importar dataframe

In [2]:
DATA_PROCESSED_ROUTE = r"../data/processed/df_processed.csv"

In [3]:
df = pd.read_csv(DATA_PROCESSED_ROUTE, dtype={"StateHoliday": str})

## Separar el DF en train y test

In [4]:
df_train = df[
    df["Date"] < "2015-01-01"
]

In [5]:
df_test = df[
    df["Date"] >= "2015-01-01"
]

## Eliminar Date

Los modelos no pueden interpretar fechas

In [6]:
df_train = df_train.drop(columns=["Date"])

In [7]:
df_test = df_test.drop(columns=["Date"])

## Separar X_train, X_test, y_train, y_test

In [8]:
X_train = df_train.drop(columns=["Sales"])
y_train = df_train["Sales"]

In [9]:
X_test = df_test.drop(columns=["Sales"])
y_test = df_test["Sales"]

## Obtener dummies

In [10]:
X_train = pd.get_dummies(X_train)

In [11]:
X_test = pd.get_dummies(X_test)

## Alinear

In [12]:
X_train, X_test = X_train.align(X_test, join="left", axis=1, fill_value=0)

## Modelado

### Linear Regression V1

Instanciar

In [13]:
model_linear_regression_v1 = LinearRegression()

Entrenar

In [14]:
model_linear_regression_v1.fit(X_train, y_train)

LinearRegression()

Predecir (tanto para train y test)

In [15]:
y_pred_linear_regresion_v1_train = model_linear_regression_v1.predict(X_train)

In [16]:
y_pred_linear_regresion_v1_test = model_linear_regression_v1.predict(X_test)

Evaluar (de forma porcentual)

Evaluamos asi porque si la prediccion es 100 y el valor real 200, es un gran error, pero si la prediccion es 1000 y el real 1100 no lo es tanto

También evaluaremos el aprendizaje en train, para detectar overfitting

In [17]:
mape_linear_regression_v1_train = mean_absolute_percentage_error(y_train, y_pred_linear_regresion_v1_train)

In [18]:
mape_linear_regression_v1_test = mean_absolute_percentage_error(y_test, y_pred_linear_regresion_v1_test)

In [19]:
print(f"Mape LinearRegression V1 train: {mape_linear_regression_v1_train * 100:.2f}%")

Mape LinearRegression V1 train: 16.11%

In [20]:
print(f"Mape LinearRegression V1 test: {mape_linear_regression_v1_test * 100:.2f}%")

Mape LinearRegression V1 test: 15.13%

### RandomForestRegressor V1

Instanciar

In [21]:
# n_jobs=-1 solo para que sea más rápido
model_random_forest_regressor_v1 = RandomForestRegressor(n_jobs=-1)

Entrenar

In [22]:
model_random_forest_regressor_v1.fit(X_train, y_train)

RandomForestRegressor(n_jobs=-1)

Predecir

In [23]:
y_pred_random_forest_regressor_v1_train = model_random_forest_regressor_v1.predict(X_train)

In [24]:
y_pred_random_forest_regressor_v1_test = model_random_forest_regressor_v1.predict(X_test)

Evaluar

In [25]:
mape_random_forest_regressor_v1_train = mean_absolute_percentage_error(y_train, y_pred_random_forest_regressor_v1_train)

In [26]:
mape_random_forest_regressor_v1_test = mean_absolute_percentage_error(y_test, y_pred_random_forest_regressor_v1_test)

In [27]:
print(f"Mape RandomForestRegressor V1 train: {mape_random_forest_regressor_v1_train * 100:.2f}%")

Mape RandomForestRegressor V1 train: 3.12%

In [28]:
print(f"Mape RandomForestRegressor V1 test: {mape_random_forest_regressor_v1_test * 100:.2f}%")

Mape RandomForestRegressor V1 test: 9.80%

### XGBRegressor V1

Instanciar

In [29]:
model_xgboost_v1 = XGBRegressor()

Entrenar

In [30]:
model_xgboost_v1.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

Predecir

In [31]:
y_pred_xgboost_v1_train = model_xgboost_v1.predict(X_train)

In [32]:
y_pred_xgboost_v1_test = model_xgboost_v1.predict(X_test)

Evaluar

In [33]:
mape_xgboost_v1_train = mean_absolute_percentage_error(y_train, y_pred_xgboost_v1_train)

In [34]:
mape_xgboost_v1_test = mean_absolute_percentage_error(y_test, y_pred_xgboost_v1_test)

In [35]:
print(f"Mape xgboost V1 train: {mape_xgboost_v1_train * 100:.2f}%")

Mape xgboost V1 train: 8.65%

In [36]:
print(f"Mape xgboost V1 test: {mape_xgboost_v1_test * 100:.2f}%")

Mape xgboost V1 test: 10.47%

### RandomForestRegressor V2

(Cabe aclarar que no se toca LinearRegression debido a que no hay mucho hiperparametro que tocar)

Instanciar con tuning

In [37]:
model_random_forest_regressor_v2 = RandomForestRegressor(
    n_estimators=300,
    max_depth=25,
    min_samples_leaf=15,
    n_jobs=-1
)

Entrenar

In [38]:
model_random_forest_regressor_v2.fit(X_train, y_train)

RandomForestRegressor(max_depth=25, min_samples_leaf=15, n_estimators=300,
                      n_jobs=-1)

Predecir

In [39]:
y_pred_random_forest_regressor_v2_train = model_random_forest_regressor_v2.predict(X_train)

In [40]:
y_pred_random_forest_regressor_v2_test = model_random_forest_regressor_v2.predict(X_test)

Evaluar

In [41]:
mape_random_forest_regressor_v2_train = mean_absolute_percentage_error(y_train, y_pred_random_forest_regressor_v2_train)

In [42]:
mape_random_forest_regressor_v2_test = mean_absolute_percentage_error(y_test, y_pred_random_forest_regressor_v2_test)

In [43]:
print(f"Mape RandomForestRegressor V2 train: {mape_random_forest_regressor_v2_train * 100:.2f}%")

Mape RandomForestRegressor V2 train: 7.27%

In [44]:
print(f"Mape RandomForestRegressor V2 test: {mape_random_forest_regressor_v2_test * 100:.2f}%")

Mape RandomForestRegressor V2 test: 10.00%

### XGBRegressor V2

Instanciamos con tuning

In [45]:
model_xgboost_v2 = XGBRegressor(
    learning_rate=0.2,
    n_estimators=600,
    max_depth=9,
    subsample=0.7,
    colsample_bytree=0.8
)

Entrenar

In [46]:
model_xgboost_v2.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.2, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=9,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=600,
             n_jobs=None, num_parallel_tree=None, ...)

Predecir

In [47]:
y_pred_xgboost_v2_train = model_xgboost_v2.predict(X_train)

In [48]:
y_pred_xgboost_v2_test = model_xgboost_v2.predict(X_test)

Evaluar

In [49]:
mape_xgboost_v2_train = mean_absolute_percentage_error(y_train, y_pred_xgboost_v2_train)

In [50]:
mape_xgboost_v2_test = mean_absolute_percentage_error(y_test, y_pred_xgboost_v2_test)

In [51]:
print(f"Mape xgboost V2 train: {mape_xgboost_v2_train * 100:.2f}%")

Mape xgboost V2 train: 5.08%

In [52]:
print(f"Mape xgboost V2 test: {mape_xgboost_v2_test * 100:.2f}%")

Mape xgboost V2 test: 9.94%

## Feature importance

### RandomForestRegressor V2

In [53]:
feature_importance_random_forest = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": model_random_forest_regressor_v2.feature_importances_
})

In [54]:
feature_importance_random_forest.sort_values(by="Importance", ascending=False)

                           Feature  Importance
20                 rolling_mean_14    0.510311
15                           lag_1    0.149788
3                            Promo    0.128788
1                        DayOfWeek    0.063722
21                 rolling_mean_30    0.047554
11                             Day    0.024175
14                            Week    0.014240
25                  rolling_std_30    0.013700
12                           Month    0.005252
19                  rolling_mean_7    0.005025
18                          lag_30    0.004735
30                     StoreType_a    0.003745
16                           lag_7    0.003554
24                  rolling_std_14    0.003224
17                          lag_14    0.003214
23                   rolling_std_7    0.003141
5              CompetitionDistance    0.003086
22                   rolling_std_3    0.002649
0                            Store    0.002064
4                    SchoolHoliday    0.001327
7         CompetitionOpenSinceYear    0.000957
6        CompetitionOpenSinceMonth    0.000849
38   PromoInterval_Jan,Apr,Jul,Oct    0.000748
9                  Promo2SinceWeek    0.000707
13                            Year    0.000692
10                 Promo2SinceYear    0.000489
35                    Assortment_b    0.000472
33                     StoreType_d    0.000452
31                     StoreType_b    0.000360
34                    Assortment_a    0.000306
36                    Assortment_c    0.000250
32                     StoreType_c    0.000231
37   PromoInterval_Feb,May,Aug,Nov    0.000066
8                           Promo2    0.000053
40           PromoInterval_NoPromo    0.000050
39  PromoInterval_Mar,Jun,Sept,Dec    0.000024
2                             Open    0.000000
29                  StateHoliday_c    0.000000
26                  StateHoliday_0    0.000000
27                  StateHoliday_a    0.000000
28                  StateHoliday_b    0.000000

### XGBRegressor V2

In [55]:
feature_importance_xgboost = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": model_xgboost_v2.feature_importances_
})

In [56]:
feature_importance_xgboost.sort_values(by="Importance", ascending=False)

                           Feature  Importance
3                            Promo    0.298507
20                 rolling_mean_14    0.223451
15                           lag_1    0.114641
21                 rolling_mean_30    0.058999
1                        DayOfWeek    0.041700
30                     StoreType_a    0.024679
26                  StateHoliday_0    0.023407
31                     StoreType_b    0.021413
35                    Assortment_b    0.019877
14                            Week    0.017690
27                  StateHoliday_a    0.016445
11                             Day    0.013450
12                           Month    0.011231
28                  StateHoliday_b    0.008032
25                  rolling_std_30    0.006914
38   PromoInterval_Jan,Apr,Jul,Oct    0.006901
32                     StoreType_c    0.006801
13                            Year    0.006659
4                    SchoolHoliday    0.006061
33                     StoreType_d    0.005419
36                    Assortment_c    0.004825
19                  rolling_mean_7    0.004555
34                    Assortment_a    0.004497
23                   rolling_std_7    0.003907
37   PromoInterval_Feb,May,Aug,Nov    0.003705
29                  StateHoliday_c    0.003616
24                  rolling_std_14    0.003561
8                           Promo2    0.003480
22                   rolling_std_3    0.003478
18                          lag_30    0.003370
10                 Promo2SinceYear    0.003296
5              CompetitionDistance    0.003232
40           PromoInterval_NoPromo    0.003144
9                  Promo2SinceWeek    0.003002
17                          lag_14    0.002939
7         CompetitionOpenSinceYear    0.002879
16                           lag_7    0.002821
39  PromoInterval_Mar,Jun,Sept,Dec    0.002793
0                            Store    0.002321
6        CompetitionOpenSinceMonth    0.002300
2                             Open    0.000000